Feature/ev3 us sensor
orwell-int/robots-ev3 pull request #3
Opened 2017-04-02 17:57 UTC by miludmann

Add support of EV3 ultrasound sensor
Add support of EV3 colour sensor for capturing flags
Remove RFID support
Add colour sampler to build a config file
Add UDP broadcast support to simplify connection to proxy

2017-04-13 21:03 UTC, dchilot requested changes
There might be a few things you could check and would like to change.

2017-04-13 21:03 UTC, dchilot commented on LICENSE.txt
> +Copyright (c) 2013-2016, Members of tits-project@gmail.com
You could even put present instead of 2016.

2017-04-13 21:03 UTC, dchilot commented on robots-ev3-module/src/main/java/orwell/tank/SimpleKeyListener.java
> +public class SimpleKeyListener implements KeyListener {
This is my fault, but it should probably be SimpleEscapeKeyListener because it only listens to the escape key.

2017-04-13 21:03 UTC, dchilot commented on robots-ev3-module/src/main/java/orwell/tank/actions/GameState.java
> +        if (payload != null && payload.equalsIgnoreCase("vict")) {
Those strings would deserve constants in a common library.

2017-04-13 21:03 UTC, dchilot commented on robots-ev3-module/src/main/java/orwell/tank/config/RobotFileBom.java
> +        if (broadcastPort != 0) {
Would a > not be more appropriate than a != ?

2017-04-13 21:03 UTC, dchilot commented on robots-ev3-module/src/main/java/orwell/tank/config/RobotFileBom.java
> +        if (broadcastTimeout != 0) {
Would a > not be more appropriate than a != ?

2017-04-13 21:03 UTC, dchilot commented on robots-ev3-module/src/main/java/orwell/tank/hardware/ColourSensor.java
> +    private static final int WINDOW_SIZE = 1;
So in the end we have a complex algorithm, but a window of only 1 ?

2017-04-16 12:40 UTC, miludmann commented on LICENSE.txt
> +Copyright (c) 2013-2016, Members of tits-project@gmail.com
Right, done!

2017-04-16 12:40 UTC, miludmann commented on robots-ev3-module/src/main/java/orwell/tank/SimpleKeyListener.java
> +public class SimpleKeyListener implements KeyListener {
Right, done!

2017-04-16 12:53 UTC, miludmann commented on robots-ev3-module/src/main/java/orwell/tank/actions/GameState.java
> +        if (payload != null && payload.equalsIgnoreCase("vict")) {
True, moved them to lejos.mf.common

2017-04-16 13:05 UTC, miludmann commented on robots-ev3-module/src/main/java/orwell/tank/config/RobotFileBom.java
> +        if (broadcastTimeout != 0) {
Ok, done!

2017-04-16 13:05 UTC, miludmann commented on robots-ev3-module/src/main/java/orwell/tank/hardware/ColourSensor.java
> +    private static final int WINDOW_SIZE = 1;
Yes, for now, it works this way...

2017-04-16 13:22 UTC, miludmann commented on robots-ev3-module/src/main/java/orwell/tank/config/RobotFileBom.java
> +        if (broadcastPort != 0) {
Ok, done!

2017-04-16 14:22 UTC, dchilot approved these changes

2017-04-16 14:22 UTC, dchilot commented
There are still a few things to improve (later).

2017-04-16 14:22 UTC, merged